# DataSource Config
spring:
  redis:
    password: ZCJzcj4068321
    host: 121.43.55.23
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.55.23:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ZCJzcj4068321
    hikari:
#      connection-timeout: 60000
      max-lifetime: 50000



mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.jie.blog.pojo
  configuration:
    map-underscore-to-camel-case: true


jie:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization



